name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.5"
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Start release build
        run: flutter build apk

      - name: Copy APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: MyApp-APK
          path: build/app/outputs/flutter-apk/*.apk

      - name: Download APK Artifact
        uses: actions/download-artifact@v2
        with:
          name: MyApp-APK
          path: artifacts

      - name: Move APK Artifact
        run: |
          mkdir copied-artifact
          mv artifacts/*.apk copied-artifact/
          
      - name: Publish Copied Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Copied-APK
          path: copied-artifact/app-release.apk
