name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.5"
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Start release build for Android
        run: flutter build apk

      - name: Copy APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: MyApp-APK
          path: build/app/outputs/flutter-apk/*.apk

      - name: Start release build for iOS
        run: flutter build ios --release --no-codesign

      - name: Copy IPA Artifact
        uses: actions/upload-artifact@v2
        with:
          name: MyApp-IPA
          path: build/ios/iphoneos/Runner.app

      - name: Archive the IPA
        run: zip -r MyApp.ipa build/ios/iphoneos/Runner.app

      - name: Move IPA Artifact
        run: |
          mkdir copied-artifact
          mv MyApp.ipa copied-artifact/

      - name: Publish Copied Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Copied-IPA
          path: copied-artifact/MyApp.ipa
